### ISSUE TITLE
How much does it require？Out of memory in workflow2.json with argument element_count 2

### ISSUE THREAD

**Issue by Erwin11** [Limitex/ComfyUI-Diffusers#14]
How much does it require？Out of memory in workflow2.json with argument element_count 2
My vram is 6GB vram,  what can I do?
![屏幕截图 2024-01-07 142709](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/f5feab07-a3bb-49f8-a3ad-0a667dd155e3)
![workflow (6)](https://github.com/Limitex/ComfyUI-Diffusers/assets/6300501/8bac8e3c-5541-4dbb-be3e-512cfbfab1d6)
[out of memory.json](https://github.com/Limitex/ComfyUI-Diffusers/files/13852490/workflow.1.json)

**Comment by Limitex** [comment]
Thank you for the report. In my environment, I am developing using an RTX 2060 12GB, so I currently need 12GB of VRAM.
The issue is that when supporting StreamDiffusion, StreamDiffusion overwrites the pipeline, so it deep copies the pipeline in advance. Therefore, it is thought that this is occurring.
I think we will implement it so that deep copy can be removed in future development.
